# required for py3.7
dist: xenial
# python versions
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install numpy scipy
  - pip install pytest pytest-cov pytest-xdist pytest-mock
  - pip install codecov
# command to run tests
script: pytest
# combinations to include
after_success:
  - codecov
