# required for py3.7
dist: xenial
# python versions
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install poetry==0.12.11
  - pip install codecov
  - poetry install
# command to run tests
script:
  # tests
  - pytest
  # code format
  - black .
after_success:
  - codecov